server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.google.fr
          predicates:
            - Path=/test

        - id: equipe_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/equipe/**

        - id: membres_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/membre/**

        - id: projet_route
          uri: http://localhost:8083
          predicates:
            - Path=/api/projet/**

        - id: proposition_route
          uri: http://localhost:8084
          predicates:
            - Path=/api/proposition/**

        - id: vote_route
          uri: http://localhost:8085
          predicates:
            - Path=/api/vote/**
